services:
  opengait:
    build: .
    container_name: opengait
    volumes:
      - .:/workspace
      - /home/kera/data/gait:/data/gait
    working_dir: /workspace
    tty: true
    stdin_open: true
    shm_size: "16gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
